### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by thewh1teagle** [MediaSavvy/MediaSavvy_Wiki#9]
Does the website is open source?
I can see only the build of it in this repository.

**Comment by MediaSavvy** [comment]
Yes, the website is fully open source, but this is also the build. Changes here reflect the website in real time. 

Basically this repo contains all the code of the website and guides from the wiki, nothing is excluded. But this repo is also used to update and run the website and wiki, which is why you can see that it's the build as well.

If you still have any questions I'll be happy to answer them, or if you are still a little confused about this :)
